gpu: "1"
allow_growth: "True"
training:
  #batch size: [synth, weak, unlabel]
  batch_size: 128
  batch_size_val: 24
  n_epochs: 1 # max num epochs
  val_thresholds: [0.5] # thresholds used to compute f1 intersection in validation.
  enable_progress_bar: True
data: # change with your paths if different.
  # NOTE: if you have data in 44kHz only then synth_folder will be the path where
  # resampled data will be placed.
  metadata_file: "/nas/home/fronchini/EUSIPCO/urban-sound-class/UrbanSound8K/metadata/UrbanSound8K.csv"
  audio_dir: "/nas/home/fronchini/EUSIPCO/urban-sound-class/UrbanSound8K/audio"
  audio_max_len: 10
  fs: 44100
  net_subsample: 4
opt:
  lr: 0.001
feats:
  n_mels: 128
  n_filters: 2048
  hop_length: 1024
  n_window: 1024
  sample_rate: 44100
  f_min: 0
  f_max: 22050
net:
  kernel_size: 5
  stride: 1
  #padding: 2
  dense_drop: [0.5, 0.5]
  maxp_ks: [4, 2]
  maxp_stride: [4, 2]
  nclass: 10
  in_channel: [1, 24, 48]
  out_channel: [24, 48, 48]
  dense_in: [3456, 64]
  dense_out: [64, 10]
  

        